name: Build Arch Linux ARM with Mira on Arch Linux host

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  DOWNLOAD_URL: http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz
  WORKING_DIR: /WORKING_DIR

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Environment
        run: |
          pacman -Syu --noconfirm base-devel sudo e2fsprogs dosfstools parted libarchive uboot-tools wget curl axel util-linux xz jq zip unzip xz patch kmod jq git btrfs-progs
          mkdir -p "$WORKING_DIR"

      - name: Download Arch Linux ARM tarball
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          axel -q4n 5 ${{ env.DOWNLOAD_URL }} -o ArchLinuxARM-aarch64.tar.gz
          axel -q4n 5 https://github.com/trapd00r/LS_COLORS/raw/master/lscolors.sh

      - name: Build Arch Linux ARM Image
        id: build
        run: |
          chmod +x $GITHUB_WORKSPACE/build.sh
          echo "BUILD_DATE=$(date +"%m%d")" >> $GITHUB_ENV
          cp -a $GITHUB_WORKSPACE/src ${{ env.WORKING_DIR }}/src
          $GITHUB_WORKSPACE/build.sh
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Release the firmware
        uses: ncipollo/release-action@main
        if: ${{ steps.build.outputs.status == 'success' && !cancelled() }}
        with:
          tag: ArchLinuxARM-aarch64_${{ env.BUILD_DATE }}
          artifacts: ${{ env.WORKING_DIR }}/BUILD_OUT/*
          allowUpdates: true
          token: ${{ secrets.GH_TOKEN }}
          body: |
            Built using Arch Linux environment.

            Default users:

            * Username: __root__ | Password: __root__
            * Username: __alarm__ | Password: __alarm__

            After booting, initialize the pacman keyring and populate the Arch Linux ARM package signing keys:

            ```
            pacman-key --init
            pacman-key --populate archlinuxarm
            ```
